### ISSUE TITLE
Model training

### ISSUE THREAD

**Issue by ImmanuvelAmalan** [Amanjeet05/attendance_system#3]
module 'cv2.cv2' has no attribute 'face_LBPHFaceRecognizer'

**Comment by rahul-patel143** [comment]
Because this module is not installed in your pc.
You need to install this using:
first you need to install this module using cmd
pip install opencv-contrib-python
then try
if it did't work
then try
first install this
python -m pip install --user opencv-contrib-python
then second install
cv2.face.LBPHFaceRecognizer_create()
